### ISSUE TITLE
Test of Facets and Tutorial

### ISSUE THREAD

**Issue by AliceChoury** [mskcc/facets#10]
Hello, 

I'm trying to run facets for a clinical application (here somatic breast tumors). 
I install the tool (v 0.5.0) and I run the first tests (with the document here : https://docs.google.com/viewer?a=v&pid=sites&srcid=ZGVmYXVsdGRvbWFpbnxtc2tmYWNldHN8Z3g6MTIxNzJkNzdjNmNjMmJjZQ) 

First I have a problem with the command line plotSample(x=oo,emfit=fit). The pdf file can not be opened and a popup appears : "The file is damaged and could not be repaired."

Then I search a tutorial or something like that (a manual with the description of the functions) and I find nothing. I don't want to try to grope for a clinical analysis. 

Thank you for your help

**Comment by veseshan** [comment]
The most likely reason for the "file damaged" message is that the file isn't complete. When you open a file to plot in R it has to be closed at the end using the dev.off() command. 

If the problem still persists please send all the relevant information so that the issue can be debugged.

Venkat

**Comment by AliceChoury** [comment]
Hello, 

I try again the test. And I have this error on my console. 

> plotSample(x=oo,emfit=fit)
Error in par(def.par) :
  invalid value specified for graphical parameter "fig"

I don't modify the code. 

Where is the problem ? 
Thank you for your help !

**Comment by veseshan** [comment]
Try:

1. delete the existing graphics window with dev.off()
2. open a new one with x11()
3. use plotSample(x=oo, emfit=fit)

In the future when you report it a problem it will lot more helpful if you provide more than just the error message.

Venkat
