### ISSUE TITLE
How to fill value for chromosome not called by facets

### ISSUE THREAD

**Issue by ShixiangWang** [mskcc/facets#111]
Hi,

After calling CNV by facets, I found some samples have no copy number values for some chromosomes.

Following is an example sample from TCGA PRAD project.

![image](https://user-images.githubusercontent.com/25057508/50672117-096ae680-1011-11e9-833a-ff8ba1504ff3.png)

**Here chromosomes 2 to 9 are not called by facets, does this mean these chromosomes are normal copy**?

I checked the same sample from SNP array, found copy number ratio of these chromosome with many probe are close to 0

![image](https://user-images.githubusercontent.com/25057508/50672180-8bf3a600-1011-11e9-84c8-b5be35daec96.png)

**Therefore, can I add these chromosome with 2** to facets results?

Thanks.

Shixiang

**Comment by veseshan** [comment]
This seems like a data issue. Please check that the read counts have all the chromosomes. It is assumed that the bam and snp files are sorted in the order 1-22, X, Y etc. If there is a mismatch in the ordering then counts will be missing for some chromosomes. For instance if the snp file is in  lexicographic order then 1 will be followed by 10-19 and then 2, 20-22, 3-9 etc. and the read counts will be missing for chromosomes 2-9.

**Comment by ShixiangWang** [comment]
I think I found the problem, in readme of snp-pipeup, you said all bam and vcf should be sorted, thus a colleague of mine sort vcf and causing this problem.

```
$ zcat hg38.snp.sort.vcf.gz | grep -v "^#" | cut -f 1 | uniq
1
10
11
12
13
14
15
16
17
18
19
2
20
21
22
3
4
5
6
7
8
9
X
Y
```

Thanks, I will close this issue and suggest you should give more clear description about this in readme.
