### ISSUE TITLE
facets focus on asan, so what is different from conventinal tool cnvkit?

### ISSUE THREAD

**Issue by kobejamescurry** [mskcc/facets#119]
Sorry, I'm bombarding you with questions... I'd like to make sure my understanding is correct.

facets focus on **asan(Allele-specific copy number analysis (ASCN))**, so what is different from conventinal tool cnvkit?  is not all gene allelie gene, sorry for the stupid question, thanks a lot

**Comment by veseshan** [comment]
Issues are meant to be specific to the software at hand. For questions regarding differences between total and allele specific (or parental) copy numbers or the basis for different algorithms it will be helpful to pose them in more relevant forums.

**Comment by kobejamescurry** [comment]
thanks for your comment, can you clarify it more clearly, I tried to find some paper describing difference, but failed. 
I do not undertand **"between total and allele specific (or parental) copy numbers "**.
just as I said, I thinks all genes are allelie gene, is that not right, thanks a lot

**Comment by kobejamescurry** [comment]
it seems that allelic-specific is more accurate and concrete than just calculating total .
so why still so many people not using asan cnv tool, but using cnvkit.
thanks a lot
![image](https://user-images.githubusercontent.com/46668881/54211604-90aa6e00-451c-11e9-9366-b66a6ad54170.png)
