### ISSUE TITLE
Replicate manuscript figure 2

### ISSUE THREAD

**Issue by xtmgah** [mskcc/facets#12]
Hello, We want to reproduce the results on Figure 2 by using TCGA chRCC patient sample (TCGA-KN-8425). We are perform the input files using the following command:

```
snp-pileup -p -g -q 10 -Q 10 -r20,0 /DCEG/Projects/SKCM/Ref/facets/hg38_00-common_all.vcf TCGA-KN-8425_20_0.pileup.txt TCGA-KN-8425-11A-01D-231
0-10_Illumina_gdc_realn.bam TCGA-KN-8425-01A-11D-2310-10_Illumina_gdc_realn.bam
```
and we do the following in R: 
```
i=20
rcmat=readSnpMatrix(paste0("TCGA-KN-8425_",i,"_0.pileup.txt.gz"))
xx <- preProcSample(rcmat)
oo <- procSample(xx,cval=150)
oo$dipLogR
fit <- emcncf(oo)
head(fit$cncf)
fit$purity
fit$ploidy
plotSample(x=oo,emfit=fit,sname = paste0("TCGA-KN-8425_",i,"_0"))
```

But we can't reproduce figure2, we found additional monosomes of cha 3 at clonal level, but we didn't find any monosomes at sub clonal level. Could you show you script to help us to reproduce figure 2? 
(purity=0.76, ploidy=1.52, dipLogR=0.29)

Thanks.

**Comment by veseshan** [comment]
There appear to be two major differences. 

The bam files we downloaded from CGhub were aligned against GRCh37 whereas are you are doing snp-pileup using hg38 snps. Do we have the same bams?

We used the filters -q15 -Q20 for the read counts. This can have a major impact on the read counts.
Additionally we had used the earlier perl script with samtools-0.1.19 (which shouldn't matter much).

Venkat

**Comment by veseshan** [comment]
By the way the sample in the paper is TCGA-KL-8331 and not TCGA-KN-8225. That could the source of the discrepancy.

Venkat
