### ISSUE TITLE
NA purity, in a sample with several CNV estimates

### ISSUE THREAD

**Issue by sahilseth** [mskcc/facets#126]
I have a whole-exome sample where facets is not able to calculate purity/ploidy properly. Is it because it is not choosing many heterozygous SNPs for estimation?

![image](https://user-images.githubusercontent.com/684975/54871604-d3720e80-4d84-11e9-8e0f-add6a032405e.png)

Here is the output from exomeCN (non-allele specific CNV caller).

<img width="985" alt="Screen Shot 2019-03-23 at 4 04 25 PM" src="https://user-images.githubusercontent.com/684975/54871635-6b6ff800-4d85-11e9-86c7-ab5586e4b9db.png">

**Comment by veseshan** [comment]
It seems like the read count matrix is rather sparse (both logR and logOR). If the average coverage depth of the sample is low you should lower ndepth in preProcSample to include more loci. Please also check that you are indeed getting proper read count matrix.

**Comment by sahilseth** [comment]
You are right depth is low, esp for the normal sample, will adjust and try again. Also normal sample is FFPE (tumor is fresh frozen), does that also complicate things?

**Comment by veseshan** [comment]
ffpe vs fresh-frozen can lead to insert size mismatch that can show up as  waterfall like artifact in log-ratio

**Comment by sahilseth** [comment]
thanks for the clarification
