### ISSUE TITLE
Error: package 'pctGCdata' 0.2.0 was found, but >= 0.3.0 is required by 'facets'

### ISSUE THREAD

**Issue by brucemoran** [mskcc/facets#127]
Hi,

I am getting error in subject line for new version of `pctGCdata` required, but only 0.2.0 is available on Github?

EDIT:
version 0.3.0 is mentioned at [https://github.com/mskcc/pctGCdata](https://github.com/mskcc/pctGCdata) but specified as coming from https://github.com/soccin/mkGCPct, and as being experimental.

Can you specify how to install 0.3.0, or release it? Or allow 0.2.0 in current facets version?

Many thanks,

Bruce.

**Comment by veseshan** [comment]
I just tested it with the command devtools::install_github("mskcc/facets") and it seems to be working fine. 

As for this comment 

>version 0.3.0 is mentioned at https://github.com/mskcc/pctGCdata but specified as coming from https://github.com/soccin/mkGCPct, and as being experimental.

v0.3.0 was created so that users can use facets on non-human/mouse genome, The code in https://github.com/soccin/mkGCPct gives the tools needed to create GC percentage data for it.

**Comment by brucemoran** [comment]
Installing `facets` with commit 3099485a4d96f09dbcacf5ba1710361fbb234f9a (v0.5.6)  allows running as normal, and standard install of pctGCdata is v0.3.0. 

```
devtools::install_github("mskcc/pctGCdata", build_vignettes = FALSE, dependencies=FALSE)
devtools::install_github("mskcc/facets", build_vignettes = FALSE, ref="3099485a4d96f09dbcacf5ba1710361fbb234f9a", dependencies=FALSE)
```

Working with `shub://brucemoran/Singularity:facets.centos7`. Apologies for time-waste,

Bruce
