### ISSUE TITLE
Ploidy not updated while tracing emcncf

### ISSUE THREAD

**Issue by dvenet** [mskcc/facets#129]
The ploidy estimate given is not updated during the tracing - for instance:

>  fit=emcncf(oo, min.nhet=tty[1], maxiter=10, trace=TRUE);
iter: 1 
dif: 0.1709942 
purity: 0.7877296 
ploidy: 2 
iter: 2 
dif: 0.07670063 
purity: 0.7877296 
ploidy: 2 
iter: 3 
dif: 0.01715529 
purity: 0.7877296 
ploidy: 2 
iter: 4 
dif: 0.01539139 
purity: 0.7877296 
ploidy: 2 
iter: 5 
dif: 0.007043781 
purity: 0.7877296 
ploidy: 2 
iter: 6 
dif: 0.005353876 
purity: 0.7877296 
ploidy: 2 
iter: 7 
dif: 0.005224373 
purity: 0.7877296 
ploidy: 2 
iter: 8 
dif: 0.004832115 
purity: 0.7877296 
ploidy: 2 
iter: 9 
dif: 0.002994015 
purity: 0.7877296 
ploidy: 2 
iter: 10 
dif: 0.002740225 
purity: 0.7877296 
ploidy: 2 
> fit$purity
[1] 0.7877296
> fit$ploidy
[1] 4.196863

**Comment by shenmskcc** [comment]
Ploidy is not updated in the EM algorithm for the integer copy number
calls. It is calculated at the end based on the 2-copy state (dipLogR) and
the purity estimate from the EM update.

Ronglai
