### ISSUE TITLE
Question: Should remove duplicates before using facets?

### ISSUE THREAD

**Issue by ShixiangWang** [mskcc/facets#148]
Dear developer, 

I use WES data for both copy number calling and mutation calling. One key step of GATK is MarkDuplicates, which removes duplicates like PCR duplicates. Should I input bam file before or after MarkDuplicates?

Best,
Shixiang

**Comment by veseshan** [comment]
You should use the bam with MarkDuplicates set so that pcr duplicates are not counted in the depth.

**Comment by ShixiangWang** [comment]
Got it, thanks for the reply.
