### ISSUE TITLE
Clarification about FACETS input

### ISSUE THREAD

**Issue by hcraT** [mskcc/facets#15]
Hi,
I would like to get a clarification about the input that facets expects.

In the vignette I read:

An input file called stomach.snpmat is generated that include six columns:
1. chormosome
2. position
3. normal sample read depth
4. normal sample variant allele count
5. tumor read depth
6. tumor variant allele read count

However when I check the input file it is clear that the 4th and 6th fields are instead the reference allele read count both for normal and tumor sample (and this is confirmed by checking in the snp-pileup.pl script). I've tried to run facets segmentation with both types of input and it doesn't seems to make much difference (I suppose beacause of the symmetry you have if you consider homozygous or hetherozygous SNPs). There are however some differences in the segmentation I think when you have SNPs with AFs that are distant from 0, 0.5 or 1.

My question is then: which is the correct (expected) input to facets? Reference or alternative read counts?

Thank you very much!

**Comment by veseshan** [comment]
Are you using the vignette from https://sites.google.com/site/mskfacets/ 
The github version of the code has bug fixes and code improvements. The current version has C++ code to do the pileup and it gives ref, alt, del and error (unlike the perl version). The vignette is also updated accordingly. You should use the latest vignette (it is built when the package is installed).

**Comment by hcraT** [comment]
Hi,
I was indeed using the version from google sites.

I will then use the github version.

Thanks for the clarification!
