### ISSUE TITLE
Setting purity=1

### ISSUE THREAD

**Issue by RoniHaas** [mskcc/facets#174]
Hello,

I was wondering if there is an option to define the purity as 1. If yes, could you please share how?

Thank you very much!

**Comment by veseshan** [comment]
If tumor purity is 1 then any segment with LOH (loss of heterozygosity) will have one of the allele missing. This will blow up the odds ratio and can cause computational issues. I have never encountered a sample with purity of 1. But if you have one I would like to see if the algorithm works or crashes. Thanks.

**Comment by RoniHaas** [comment]
Thank you for your answer!

I am using prostate tumor cell lines, and it is hard to believe that these samples aren’t close to 100% purity.

These are WGS samples. My normal samples are unmatched random blood samples, with about the same coverage.


When I used FACETS with the code below, the resulted purity was too low for cell lines, 0.3 - 0.5.

```
rcmat <- readSnpMatrix(sample.pileup);
rcmat[which(rcmat$Chromosome == '23'), 1] <- 'X';
xx <- preProcSample(
    rcmat,
    snp.nbhd = 2500,
    unmatched = TRUE,
    het.thresh = 0.1
    );
oo <- procSample(
    xx,
    cval = 1500
    );
fit <- emcncf(oo)
```

I am happy to try the solution of purity=1 and let you know if the algorithm works or crashes.

If you could suggest how to change the code to set purity=1 that would be very helpful. Thanks!

**Comment by veseshan** [comment]
Can you provide an example figure? Cell lines are notoriously fragmented and noisy.

**Comment by RoniHaas** [comment]
Sure, thank you for the help!

ploidy 2.8  purity 0.36
 
![image](https://user-images.githubusercontent.com/39231609/162808178-6d7c323a-da41-4e94-9a61-a08e64dbb883.png)

Just one note about that. I did a small modification to your code.
With --unmatched there is a requirement for tumor read [coverage >=50](https://github.com/mskcc/facets/blob/f3c93ee65b09fc57aaed22a2eb9faa05586a9dc0/R/facets-procreads.R#L21).
 
That created lots of "gaps" where no SNPs are presented in the logOR panels. Since it was hardcoded, I changed the code manually locally for coverage >=25. That solved the problem (example below).

E.g. Before my change with the original code
![image](https://user-images.githubusercontent.com/39231609/159611445-f9b7abb1-c9bc-4a66-9f6e-c64a084be410.png)

E.g. using my code with coverage >=25:
![image](https://user-images.githubusercontent.com/39231609/162808633-3924b1bc-1a0c-4a28-a122-3987538ba89a.png)

**Comment by veseshan** [comment]
Cell lines are always problematic. For instance you can see both chr1p and chr3p have both balanced (log-odds-ratio close to 0) and imbalanced  (log-odds-ratio around +/-2) interspersed throughout. This doesn't make any sense and the algorithm goes somewhere in the middle. I am sorry I don't have a good solution for weird scenarios like this.

**Comment by RoniHaas** [comment]
Thank you, I appreciate your help
