### ISSUE TITLE
snp-pileup throws non 0 error code on successful exit

### ISSUE THREAD

**Issue by lordzappo** [mskcc/facets#19]
Hello,

Can this code please return 0 on success, rather than 161

snp-pileup -A -g dbsnp_137.b37__RmDupsClean__plusPseudo50__DROP_SORT.vcf.gz countsMerged____H_LS-A8-A094-01A-11W-A019-09-1__H_LS-A8-A094-10A-01W-A021-09-1.dat.gz Chr22_hg19_TCGA-A8-A094-01A-11W-A019-09.tumor.bam Chr22_hg19_TCGA-A8-A094-10A-01W-A021-09.normal.bam
Finished in 171.420000 seconds.

charris@selene ~/code/cmo/bin>echo $?
161

**Comment by veseshan** [comment]
The code has a "return 0;" line at the end. So I don't know why you are getting 161. (An earlier version did not but was added a while ago.)

Unrelated comment - readSnpMatrix assumes File1 is normal and File2 is tumor. So you should switch the order of the bam file in the call.

Venkat

**Comment by lordzappo** [comment]
git pull + recompile fixes, thanks
