### ISSUE TITLE
Bugs for the new version 0.5.6

### ISSUE THREAD

**Issue by xtmgah** [mskcc/facets#22]
Hello:
I run the new version of facets but i got the following error:

xx <- preProcSample(rcmat)
Error: NA/NaN/Inf in foreign function call (arg 7)
In addition: Warning messages:
1: In { : NAs produced by integer overflow
2: In { : NAs produced by integer overflow

Can you fix this error? thanks.

**Comment by veseshan** [comment]
It is hard for me to fix an error I cannot produce. Can you provide a data file that will trigger this error.

Thanks,
Venkat

**Comment by xtmgah** [comment]
Hey:

I try the old version 0.5.2 and 0.5.5, it's all working. I think the problem is only in newest version..  The data i used is WGS data (the input compressed pileup files is about 250 Mb). and i try to random selected 5% data, and it's working perfect... So i don't know why the large dataset have an issues for "preProcSample".  

Do you have any idea what's the different between 0.5.2 and 0.5.5 (the major function) or only increase the performance?

**Comment by veseshan** [comment]
Can you tell me how many lines are in rcmat? Can you also try preProcSample with snp.nbhd=1000 instead of the default 250 and see if that works? I am trying to see if the WGS is producing too many SNPs that's causing the integer overflow.

Thanks,
Venkat

**Comment by xtmgah** [comment]
we try snp.nbhd=2000 and it still cause this problem... the are totally 32993554 lines in rcmat... if you need, i can send the totally pileup file...

**Comment by veseshan** [comment]
I have fixed the lines of code that I think is causing the problem. Let me know if it works now. Thanks.

Venkat

**Comment by xtmgah** [comment]
Hey:

I just try it and it work perfect. I think you already fixed this problem. Thanks for your help.
