### ISSUE TITLE
Output columns

### ISSUE THREAD

**Issue by xtmgah** [mskcc/facets#24]
Hello:

I use facets to do the segmentation and get the output from the following script:

```R
rcmat=readSnpMatrix(input)
xx <- preProcSample(rcmat,ndepth = ndepth,cval = cval,snp.nbhd = snp.nbhd)
oo <- procSample(xx,cval=cval2)
fit <- emcncf2(oo)
```

Here is one line of fit$cncf, Can you tell me what's the means of "maR" and  "cnlr.median.clust"?, what's the difference between "cnlr.median.clust" and "cnlr.median". If i want to make a heatmap plot for few samples, which value should i use to show the copy number? Thanks.  

```
$1	chrom            	1
$2	seg              	5
$3	num.mark         	264
$4	nhet             	164
$5	cnlr.median      	-0.189885244556454
$6	mafR             	0.227417480392143
$7	segclust         	15
$8	cnlr.median.clust	-0.189885244556454
$9	mafR.clust       	0.227417480392143
$10	start            	121350213
$11	end              	143291855
$12	cf.em            	1
$13	tcn.em           	2
$14	lcn.em           	1
$15	clonal.cluster   	1

```

**Comment by veseshan** [comment]
Aren't these all explained in the help file for procSample and emcncf?

**Comment by veseshan** [comment]
cnlr.median is estimated from each segment.The clust versions is obtained after clustering the segs to ones with similar characteristics

**Comment by Rashesh7** [comment]
Hi, 
I have the same question. I checked the help file for procSample and emcncf, but it just explains the cf, tcn and lcn (and their EM counterparts). emcncf2 has the clonal.cluster.

Can you please add some descriptions for the other Variables. 

Thank you.

**Comment by veseshan** [comment]
I have added a description of the columns in the procSample help.
