### ISSUE TITLE
mouse "chr20 zero snps" error

### ISSUE THREAD

**Issue by lordzappo** [mskcc/facets#26]
Loading required package: pctGCdata
Error in segsnps(dmat, cval, hetscale) : chr20 has ZERO snps
Calls: facets_iteration -> preProcSample -> segsnps
Execution halted

Mouse has 1-19, X,Y, so should the segsnps method be altered slightly?  My counts file certainly has 1-19, X, and Y.  

@soccin- have you run into this before?

**Comment by soccin** [comment]
No I have do not remember getting this but the previous time I got facets to run on mouse I was using a version of the MM9 VCF which only had the autosomes (1-19). I have not gotten the full MM10 (1-19,X,Y) to work.

**Comment by veseshan** [comment]
Can you make a read count file available so that I can debug.

Thanks,
Venkat

**Comment by lordzappo** [comment]
https://drive.google.com/open?id=0BwHVbia0ABwDY29QZlE0cjhLY2s

225mb so i went with google drive for transfer

**Comment by soccin** [comment]
Can you send the path to it on LUNA. That might be easier than google drive. 

thanks

n

**Comment by veseshan** [comment]
@Nick - thanks for beating me to it

**Comment by lordzappo** [comment]
didn't realize you had access to luna- /ifs/work/charris/mm10_test

**Comment by veseshan** [comment]
As an aside - you should use the --min-counts in snp-pileup. Most of the lines in the read counts are singletons. Even 10,0 can greatly reduce the file size.

> table(rcmat$NOR.DP >= 10)

   FALSE     TRUE 
46385291  3602293

**Comment by veseshan** [comment]
I got no error (version 0.5.6 as in GitHub). My commands:

rcmat <- readSnpMatrix("GCL/countsMerged____s_MB49DNA__s_C57BL6_Germline.dat.gz")
xx <- preProcSample(rcmat, gbuild="mm10")
oo <- procSample(xx)

Did you specify gbuild to be mm10 or leave it as the default?

Venkat

**Comment by veseshan** [comment]
By the way the dipLogR estimate is completely off since there are almost no hets in the data (just 730 in total). So all copy number estimates are off. Needs a better way to estimate dipLogR.

**Comment by lordzappo** [comment]
You are correct, this is my mistake, we haven't used mouse before and our pipeline wasn't supplying this param at all, which worked for human.  I will make the changes.

**Comment by soccin** [comment]
This lack of het SNP may be a general problem for mouse due to the inbreed strains. Another use case for the non-allele specific method we talked about.

**Comment by veseshan** [comment]
Then FACETS will probably give the wrong answers all the time. We should think about restricting FACETS to cases with sufficient het SNPs (at at least 5% of snps should be hets) and do a pure total copy number package for these cases and low-pass WGS.
