### ISSUE TITLE
Changing the thresholds

### ISSUE THREAD

**Issue by Rashesh7** [mskcc/facets#32]
Hello,

This is pretty neat and usefull too. I am testing it to add it to our pipeline. 

1) I was wondering on how you came up with the thresholds for ndepth and cval dor the preProcSample and procSample.

2) And is there any way to estimate what thresholds to use for a particular sample.(like any dependence on the QC metrics) 

Your input and suggestions are greatly appreciated.

**Comment by veseshan** [comment]
ndepth was chosen based on the average coverage (about 150x) in the TCGA samples we analyzed. Likewise the cval worked well there. If the coverage is higher you could/should increase ndepth to eliminate unreliable loci. As for cval, it is easy to refit the data with different cval. Usually it doesn't have a major impact on good samples but larger values help ameliorate hyper-fragmentation in not so good ones.

**Comment by Rashesh7** [comment]
Oh ok. Yeah, I saw the discussion on this for WGS samples in #16.

I agree since the tool runs very quickly, we could refit the data  using different cval. 

But I was just wondering, if there was a way to predict the threshold before running the tool, like from library QC etc.

**Comment by veseshan** [comment]
There is no way to predict the cval threshold based on quality metrics.

**Comment by Rashesh7** [comment]
Hello,

Are the cnlr.median values, provided in the fit$cncf, adjusted for purity and ploidy? If it is adjusted for purity and ploidy is there a way to get to the original values pre-adjustment?

Thank you.

**Comment by shenmskcc** [comment]
cnlr.median is the original logR seg median, not adjusted for purity and
ploidy.
