### ISSUE TITLE
  no non-missing arguments to max; returning -Inf

### ISSUE THREAD

**Issue by jiahaochenplus** [mskcc/facets#33]
when i was running fit=emfncf(x), got error message:
In max(mafR.clust[seg$chrom < nX], na.rm = T) :
  no non-missing arguments to max; returning -Inf
----
Then for the values in mafR.clust and lcn.em is NA.

**Comment by jiahaochenplus** [comment]
I figured out the problem. The 'datafile' needed to be sorted before running the package. The original output from snp-pileup is sorted, but i used my own script/commands for the filtering, which changed the order.

Thank you!
-JC

**Comment by veseshan** [comment]
Thanks. The data needs to be sorted by chromosome and position.
