### ISSUE TITLE
snp-pileup issue

### ISSUE THREAD

**Issue by compgenome365** [mskcc/facets#34]
Hi,
I'm getting memory error (I think due to invalid free()) when I'm trying snp-pileup to generate the input data for facets.
Is it a known issue ? or how to resolve it ?
Thanks,
--Subhajit

**Comment by veseshan** [comment]
No one has reported such an error before. It is impossible even to begin thinking of possible causes without any information on the operating system and compiler versions. The code requires that the compiler be c++11 standards compliant.

Venkat

**Comment by compgenome365** [comment]
Hi Venkat,

Thanks for your prompt reply. I'm just asking you in case you are aware of this problem be

From the error log it seems the error is getting generated by htslib (1.3.1). 
OS: CentOS 6.8 and compiler: g++ 4.4.7-17

I compiled with -std=c++0x flag

The following is the gdb trace. 
Again thanks for any insight in case you have seen this.

(gdb) bt
#0  0x00000034582325e5 in raise () from /lib64/libc.so.6
#1  0x0000003458233dc5 in abort () from /lib64/libc.so.6
#2  0x00000034582704f7 in __libc_message () from /lib64/libc.so.6
#3  0x0000003458275f3e in malloc_printerr () from /lib64/libc.so.6
#4  0x0000003458278dd0 in _int_free () from /lib64/libc.so.6
#5  0x00007ffff7b3f4f4 in inflateEnd () from /home/sengups/zlib_install/lib/libz.so.1
#6  0x00007ffff7d882e7 in decompress_peek (fp=<value optimized out>, dest=<value optimized out>, destsize=21) at hts.c:148
#7  0x00007ffff7d8850f in hts_detect_format (hfile=0x646c10, fmt=0x7fffffffda70) at hts.c:193
#8  0x00000000004025b2 in program_main(arguments) ()
#9  0x0000000000403e84 in main ()

**Comment by veseshan** [comment]
Unfortunately I am unable to offer any assistance regarding this htslib compilation issue. Have you tried their mailing list.

Additionally g++ 4.4.7 may not be able to support the c++11 which snp-pileup needs. (seems like you have changed the flag to std=c++0x)

Venkat
