### ISSUE TITLE
tumor-only samples or tumor with unmatched normal samples

### ISSUE THREAD

**Issue by JoKw** [mskcc/facets#41]
Hi, Can facets be used for tumor-only samples or tumor with unmatched normal samples? Thanks

**Comment by veseshan** [comment]
There is an "unmatched" option in preProcSample which can be used for such an analysis. The pileup should be done with the pooled/unmatched normal. This is not well tested and hence feedback will be appreciated.

Venkat

**Comment by alejandro-jimenezsanchez** [comment]
Hi,

I would like to run facets with unmatched normal samples too.

I ran snp-pileup as:
`snp-pileup $vcf 1_snppileup.csv $bam`

And I got the csv file with the columns:

`Chromosome,Position,Ref,Alt,File1R,File1A,File1E,File1D`

When I do:

`rcmat = readSnpMatrix(datafile)`

I get the warning message:

`In read.table(file = file, header = header, sep = sep, quote = quote,  :
  cols = 8 != length(data) = 12`

And rcmat has:

`[1] Chromosome Position   NOR.DP     NOR.RD     TUM.DP    
<0 rows> (or 0-length row.names)`

Also this is mouse data and the bams were aligned against mm10 reference genome.

Any help would be greatly appreciated.

Best,
Alejandro

**Comment by veseshan** [comment]
Even for tumor only you still need a normal (could be pooled normal) in the pileup. O/w facets won't work.

Venkat

________________________________________

**Comment by alejandro-jimenezsanchez** [comment]
Hi Venkat,

This is the first time I'm using facets and analysing samples without a matched normal, so I am not sure what "pooled normal" actually means. The samples I am analysing are mouse cancer cultured cells, so would a "pooled normal" be any mouse normal WES that I could find?

Thanks,
Alejandro

**Comment by vyellapa** [comment]
With pooled normals, when we run pileups multiple alleles might have reporting reads at a given loci. How does facets interpret coverage at multiple alleles in normals and coverage at only 2 alleles in tumor?

**Comment by veseshan** [comment]
In the unmatched case the allele specific normal counts are not used. Only the total is used. The tumor counts are used to ascertain heterozygous snps.

**Comment by rayliu0115** [comment]
Hi,

I also have a question about the unmatched case. I run facets and use unmatched mode with one tumor bam and three different unmatched bam respectively. However, the three results are different. If the unmatched mode only used the information of tumor bam, why are these results different? Does it mean I have to prepare one "special normal" bam when I test different tumor bams?  

Cheers,
Rui

**Comment by veseshan** [comment]
It will b helpful if you provide some details on how they are different. Unmatched option is not well tested.

**Comment by rayliu0115** [comment]
Thanks for your reply.

The main purpose of my research is to get the tumor purity and ploudy by using tumor bam only. I used some tumor-normal matched samples to test facets and tried to find out how the results would be different between matched and unmatched modes.

First, I used facets to analyze one pair of tumor-normal matched bams from PatientA and made the results as my "gold standard". Then, I used the same tumor bam from PatientA and three different normal bam from different patients respectively to run facets in the unmatched mode. 

Based on my understanding, if I used the unmatched mode, it would not matter which normal bam I used, so the three unmatched results would be same. However, the three results were huge different.

About the unmatched mode, dose facets still use information of the normal bam? Dose it mean I have to create a standard normal bam when I run facets with different tumor bam? If yes, do you have any suggest how to create a standard normal bam?

**Comment by veseshan** [comment]
Lot of words; no data. It is hard to impossible to guess what may be causing your inconsistent results,  

It is not true that the normal is not used in the unmatched mode; it's used for total copy number (log-ratio) and not for allelic imbalance (log-odds-ratio). So the normal can have an impact on your results.

**Comment by rayliu0115** [comment]
Oh, I see. Thanks so much for your help. I will keep trying

**Comment by LeiG1103** [comment]
Hi,
I have a question about creating the standard normal bam.  Can I just combine several normal bam files together as one bam file? If I do this, the sequencing depth for the normal bam will change. Will that cause any problem to compare the tumor sample with the normal file?
