### ISSUE TITLE
Output descriptions

### ISSUE THREAD

**Issue by vyellapa** [mskcc/facets#42]
I have output generated from facets. Is there a document that will describe what each of the fields mean?

1 "chrom"
2 "seg"
3 "num.mark"
4 "nhet"
5 "cnlr.median"
6 "mafR"
7 "segclust"
8 "cnlr.median.clust"
9 "mafR.clust"
10 "start"
11 "end"
12 "cf.em"
13 "tcn.em"
14 "lcn.em"

Thank you,
Teja

**Comment by veseshan** [comment]
help("procSample") and help("emcncf") give you what you want. In particular:

     out: data frame of segment summaries pre and post clustering of
          segments. The columns are: ‘chrom’ the chromosome to which
          the segment belongs; ‘seg’ the segment number; ‘num.mark’ the
          number of SNPs in the segment; ‘nhet’ the number of SNPs that
          are deemed heterozygous; ‘cnlr.median’ the median log-ratio
          of the segment; ‘mafR’ the log-odds-ratio summary for the
          segment; ‘segclust’ the segment cluster to which segment
          belongs; ‘cnlr.median.clust’ the median log-ratio of the
          segment cluster; ‘mafR.clust’ the log-odds-ratio summary for
          the segment cluster; ‘cf’ the cellular fraction of the
          segment; ‘tcn’ the total copy number of the segment; ‘lcn’
          the minor copy number of the segment.
    cncf: dataframe consisting of the columns of segmentation output as
          well as cellular fraction (cf), total (tcn) and lesser (lcn)
          copy number of each segment and their em counterpart (with
          .em suffix)

**Comment by vyellapa** [comment]
Thank you Venkat for this information. 
I am wondering if there is a way to get a "Log2FoldChange" value that is typically produced by CBS or similar algorithms in a seg file. 

I believe the "cnlr.median.clust" is a similar value. However, when the overall log ratio is not "0"(green line in the top panel of the attached figure), the entire genome looks deleted or amplified if I were to use this value. Do you have any suggestion for getting the log2 copy number values?

![i-h-100957-n1-1-d1-1](https://user-images.githubusercontent.com/1234647/26839940-81145228-4ab2-11e7-91ac-6636d4732998.png)
