### ISSUE TITLE
Unable to install on MAC OS Sierra

### ISSUE THREAD

**Issue by nkakkargit** [mskcc/facets#43]
Hi,

I am trying to install facets on my MAC (OS Sierra), but keep getting the following errors. I wonder if you guys have any solution for the same.

* preparing ‘facets’:
* checking DESCRIPTION meta-information ... OK
* cleaning src
* installing the package to process help pages
* saving partial Rd database
* **creating vignettes ... ERROR**
Loading required package: pctGCdata
Warning in emcncf2(oo) :
  emcncf2 occationally returns quirky copy number estimates due to the clonal cluster structure imposed. please use with caution.
**Error in texi2dvi(file = file, pdf = TRUE, clean = clean, quiet = quiet,  : 
  Running 'texi2dvi' on 'FACETS.tex' failed.
Calls: <Anonymous> -> texi2pdf -> texi2dvi
Execution halted
Installation failed: Command failed (1)**

**Comment by veseshan** [comment]
This may have something to do with the location of LaTeX binaries in your system (if it exists). You can see if not building the vignettes devtools::install_github("mskcc/facets", build_vignettes = FALSE) will let you install the package.

Venkat

**Comment by nkakkargit** [comment]
That worked. Thanks
