### ISSUE TITLE
where to find the value of the tumor purity of a sample?

### ISSUE THREAD

**Issue by snoopy-448** [mskcc/facets#44]
Hi, I want to use facets to calculate the tumor purity and the ASCNA, but I only got the final figure, don't know where can I find the purity value? Could you help me? Thanks!
This is my commands:
path <- paste(input_dir, file, sep = '')
 region <- strsplit(file, '.snp.')[[1]][1]
 pre_data <- preProcSample(file = path)
 data <- procSample(pre_data, cval = 150)
 fit_data <- emcncf(data)
 pdf(paste(output_dir, region, '.facet.result.pdf', sep = ''))
 plotSample(x = data, emfit = fit_data)
 dev.off()

**Comment by veseshan** [comment]
The vignette says that fit$purity and fit$ploidy give you the relevant quantities.
