### ISSUE TITLE
snp_pileup error

### ISSUE THREAD

**Issue by lalamot** [mskcc/facets#48]
Hi, 
Please  I need your help with the following
Some how when attempting to run the  "snp-pileup" using the  dbSNP downloaded  VCF from "ftp://ftp.ncbi.nlm.nih.gov/snp/organisms/human_9606_b150_GRCh38p7/VCF/00-common_all.vcf.gz", I get the following error " : 00-common_all.vcf.gz: file not recognized: File format not recognized."

**Comment by lalamot** [comment]
and this is the latest "c++" snp-pileup (not the one in perl)

**Comment by veseshan** [comment]
That VCF is a remote file on the NCBI site. You need to download it before running xnp-pileup.

Venkat

**Comment by lalamot** [comment]
Hi Venkat,
Thank you so much for the prompt response, and I apologize for not being clearer:
The VCF is downloaded and in my local working space.
Kindly,
Lala



Sent with Good (www.good.com)


-----Original Message-----

**Comment by veseshan** [comment]
Have you checked whether the VCF file was not corrupted during download? 

The snp-pileup usage is:

Usage: snp-pileup [OPTION...] <vcf file> <output file> <sequence files...>

If the file is not corrupt and the usage is right then I am at a loss as to why you are getting the error.

Venkat

**Comment by lalamot** [comment]
Thank you so much  for the prompt responses.
 All is resolved (issue was - "HTSlib"  libraries availability +  "sudo ldconfig" command,
resolved by "export LD_LIBRARY_PATH=/usr/local/lib").
 So the error was completely on my end  in the docker image environment   from which I  compiled and  now successfully running snp_pileup program .
Thank you again

**Comment by veseshan** [comment]
Glad it all worked out.
