### ISSUE TITLE
No calls made on X chromosome

### ISSUE THREAD

**Issue by Rashesh7** [mskcc/facets#51]
Hi,

Thank you for providing and maintaining this tool, it's really helpful. I am benchmarking FACETs and noticed that it did not make any calls on the X chromosome. 

Is this something by design or an issue with the way I am running? 
Any help and support is much appreciated.

Thanks,
Rashesh

**Comment by veseshan** [comment]
What kind of targeted sequencing are you using? How many loci do you have from X chromosome? You can see from the vignette that we do make calls on the X chromosome.

**Comment by Rashesh7** [comment]
Oh yeah, sorry did not look in vignette.

I am using WGS data. I have generated a set of loci using the dbsnp 137 SNVs and 1000G phase3 SNVs. But my VCF was sorted lexicographically (1,2,3...22,MT,X and Y). Due to that snp-pileup code stopped after doing MT and skipped X and Y. 

So I re-ordered the chromosomes and now it works. Does snp-pileup internally consider MT as the last chromosome?

Thanks.

**Comment by veseshan** [comment]
I don't believe snp-pileup does. But preProcSample uses 23 chromosomes for hg build (assuming that the 23rd is X) and that could have been the issue since the 23rd in your case was MT. If you still have the old pileup file you can check if any of the X chromosome SNPs are there. Another issue could be that the chromosome order in the VCF file is not the same as the bam file.

Venkat

**Comment by Rashesh7** [comment]
Hi Venkat, 
So the snp-pileup output itself skipped the X and Y chromosomes which were after MT. When I removed MT it when through correctly. If the chromosome order in the VCF file is not the same as the bam file would that affect snp-pileup?

**Comment by veseshan** [comment]
For computational efficiency reasons when the pileup presented the first MT locus after the last chr22 locus, the program had to skip through all X & Y loci in the VCF file to get to MT. If this is not done then the program will take a lot longer. Bottom line bam and VCF should be in the same order.

Venkat

**Comment by Rashesh7** [comment]
Cool. Thank you.

**Comment by Rashesh7** [comment]
Hi Venkat,

I have a question regarding one of the sample I am testing. It is a WGS sample. 
I am using the ndepth of 15, preproc CVAL 25 and proc CVAL of 200. The output is very fragmented CNV profile. 
![facets_cnv_profile](https://user-images.githubusercontent.com/4691098/31090361-67f1c7e2-a775-11e7-9ee1-952a63a58e5e.png)


Even when the logR plot shows the over all profile why does FACETs call so many segments.

The purity and average ploidy of the sample is 0.53 and 3.20. 

Can you please suggest, what might be the cause and what can I change to smoothen the profile further?

I used proc CVAL of 300 and it also shows a similar profile.

**Comment by veseshan** [comment]
You should set ndepth depending on the average coverage of the sequencing, say about 1/4 or 1/3 of the average coverage. The cval parameter for preProc and proc in WGS setting should be much higher than the default (set based on WES experience). I would suggest 50 and 500 sine the number of loci in WGS is an order of magnitude larger than that in WES. You might also want to increase the snp.nbhd from the default of 250 to say 1000.

Venkat

**Comment by Rashesh7** [comment]
Hello Venkat ,

Also for the WGS should I be using the '-P 150' argument for the snp-pileup tool? Or should I update that to another value?
