### ISSUE TITLE
facets on Liquid Biopsy

### ISSUE THREAD

**Issue by haoziyeung** [mskcc/facets#72]
Hi,i'm using facets on cfDNA sample(not FFPE),and i found the purity is NA,so i'm wondering whether facets can use on this situation?

thanks a lot.

**Comment by haoziyeung** [comment]
oh,and this is my commnad:
`/gpfs/users/yanghao/software/facets-master/inst/extcode/snp-pileup --gzip --min-map-quality 15 --min-base-quality 20 --pseudo-snps 100 --min-read-counts 25,0 /gpfs/users/yanghao/database/ncbi/dbsnp/00-common_all.vcf.gz out.cvs.gz /gpfs/users/yanghao/test/tnscope/18a0487cf-18a0487g/18a0487g.N.merge.bam /gpfs/users/yanghao/test/tnscope/18a0487cf-18a0487g/18a0487cf.T.merge.bam`

and the row count of out.csv.gz is 62463
here is head:
Chromosome,Position,Ref,Alt,File1R,File1A,File1E,File1D,File2R,File2A,File2E,File2D
1,2488000,.,.,43,0,0,0,247,0,0,0
1,2488100,.,.,77,0,0,0,1719,0,0,0
1,2488112,T,C,78,0,0,0,1847,0,3,0
1,2488153,A,G,41,39,0,0,1103,804,1,0
1,2488200,.,.,58,0,0,0,1514,0,0,0
1,2488203,C,T,56,1,1,0,1439,0,0,0
1,2489100,.,.,25,0,0,0,603,0,0,0
1,2489167,G,T,31,2,0,0,1074,4,0,0
1,2489200,C,T,39,0,0,0,1251,1,0,0
1,2489300,.,.,31,0,0,0,787,0,0,0
1,2489337,G,T,24,0,0,0,498,2,1,0
1,2489700,.,.,38,0,0,0,876,0,0,0
1,2489707,C,T,40,0,0,0,964,1,0,0
1,2489751,A,G,49,0,0,0,1329,1,2,0
1,2489768,T,C,78,0,0,0,1588,0,1,0
1,2489800,.,.,92,0,0,0,1879,0,0,0
1,2489846,C,T,103,0,0,0,2043,1,4,0
1,2489900,.,.,92,0,0,0,2374,0,0,0
1,2489962,G,A,64,0,0,0,1715,7,1,0
1,2490000,.,.,40,0,0,0,952,0,0,0
1,2491200,.,.,19,0,0,0,283,0,0,0
1,2491205,C,T,12,9,0,0,177,134,0,0
1,2491300,.,.,50,0,0,0,1273,0,0,0
1,2491306,G,A,54,0,1,0,1329,0,2,0
1,2491400,.,.,51,0,0,0,1155,0,0,0
1,2491500,.,.,20,0,0,0,435,0,0,0
1,2492100,.,.,31,0,0,0,1435,0,0,0
1,2492123,G,A,32,0,0,0,1514,0,1,0
1,2492200,.,.,23,0,0,0,1231,0,0,0
1,2493100,.,.,49,0,0,0,1178,0,0,0
1,2493136,C,T,63,0,0,0,1466,0,0,0
1,2493158,C,T,64,0,1,0,1565,1,2,0
1,2493200,.,.,80,0,0,0,2244,0,0,0
1,2493300,.,.,50,0,0,0,1811,0,0,0
1,2493360,C,T,19,0,0,0,403,0,0,0
1,2494200,.,.,48,0,0,0,915,0,0,0
1,2494300,.,.,94,0,0,0,2119,0,0,0
1,2494330,G,A,78,0,0,0,1786,0,1,0
1,2494500,.,.,42,0,0,0,937,0,0,0
1,2494561,G,A,78,0,0,0,2286,0,2,0
1,2494600,.,.,96,0,0,0,2338,0,0,0
1,2494645,C,T,108,4,0,0,2395,2,1,0
1,2494700,.,.,94,0,0,0,1420,0,0,0
1,2494718,A,G,74,0,0,0,1402,0,1,0
1,2494800,.,.,26,0,0,0,450,0,0,0
1,2494816,C,T,22,0,0,0,379,0,0,0
1,4849200,.,.,27,0,0,0,177,0,0,0
1,4849241,G,A,62,0,2,0,1077,0,5,0
1,4849300,.,.,117,0,0,0,2379,0,0,0
1,4849380,C,T,158,0,0,0,2524,4,0,0
1,4849384,T,C,159,0,0,0,2426,0,3,0
1,4849400,.,.,160,0,0,0,2434,0,0,0
1,4849405,T,C,150,0,0,0,2384,0,5,0
1,4849500,.,.,71,0,0,0,1047,0,0,0
1,4849552,C,T,31,0,0,0,325,0,0,0
1,4955700,.,.,47,0,0,0,922,0,0,0
1,4955738,A,G,89,0,0,0,1774,0,0,0
1,4955800,.,.,180,0,0,0,2453,0,0,0
1,4955810,G,A,169,0,3,0,2494,0,1,0
1,4955862,C,T,104,79,0,0,1581,1196,4,0

can cfDNA/ctDNA T-N pair sample for estimating tumor purity ? thanks very much. :)

**Comment by veseshan** [comment]
We have used FACETS on cfDNA samples. The NA for purity could be because there is no perceptible copy number change in the sample or there are too few hets. You can check the proportion of hets by looking at the het variable in jointseg (in preProcSample output).

Venkat

**Comment by haoziyeung** [comment]
Hello Venkat,here's my output [https://github.com/haoziyeung/supp_files/blob/master/out.cvs.gz](url) mentiened before,
i found the emflags is "Noisy sample, Calls can be unreliable. Insufficient information to estimate purity. Likely diplod or purity too low."

**Comment by veseshan** [comment]
Thanks for the data. The tumor fraction (purity) is indeed very low. Since copy number log-ratio depends on both tumor and normal depth of coverage, the noise is a function of the smaller of the two. Even though the median coverage for tumor is 1360 it is only 106 for normal, which affects the fit. The sample also shows waterfall effect (low log-ratio spread across the genome). Is the normal not cell-free DNA?
![out cvs](https://user-images.githubusercontent.com/12280668/36797532-2d7ad3d0-1c76-11e8-80a4-31b152292bc4.png)

**Comment by haoziyeung** [comment]
Hello,veseshan,thank for you reply,this project is designed by :cfDNA:2000x(Tumor)   gDNA:100X(Normal), this sample pair i use sequenza too,and the result of sequenza is 0.67,maybe sequenza is wrong according to your advise.

**Comment by veseshan** [comment]
Another possibility is that the tumor has no copy number changes but has mutations that can be seen in cfDNA. Sequenza can be right if there are mutations with high mutant allele frequency.

**Comment by haoziyeung** [comment]
Many thanks veseshan,i'll test facets on more samples ,it's a great tool, thanks.

**Comment by lidd77** [comment]
> Thanks for the data. The tumor fraction (purity) is indeed very low. Since copy number log-ratio depends on both tumor and normal depth of coverage, the noise is a function of the smaller of the two. Even though the median coverage for tumor is 1360 it is only 106 for normal, which affects the fit. The sample also shows waterfall effect (low log-ratio spread across the genome). Is the normal not cell-free DNA?
> ![out cvs](https://user-images.githubusercontent.com/12280668/36797532-2d7ad3d0-1c76-11e8-80a4-31b152292bc4.png)

HI, how to draw such these pictures ?  where can I get the data using FACETS ?
Thanks .
