### ISSUE TITLE
Determination of optimal parameters

### ISSUE THREAD

**Issue by lhgergo** [mskcc/facets#75]
Hi,
We would like to detect loss of heterozygosity of loci on chromosome 6 from whole exome sequencing data of tumor samples. We have already managed to install and try FACETS on one of the samples, but the resolution of results seemed to be too low. What critical value do you suggest to use to avoid oversegmentation, but to get a more detailed view on what parts of a given chromosome are missing (or not)? Or how could we determine ideal parameters for our samples?

Thanks!

**Comment by veseshan** [comment]
It is hard to understand what you mean by the resolution being too low. Detection of LOH that spans whole or part of a chromosome is easy. See for instance chromosomes 3 and 6p in the stomach cancer example in vignette. You may want to include some specifics so that we can figure out what you are looking for.

Venkat

**Comment by lhgergo** [comment]
We would like to detect LOH in the region of HLA loci. However, just when I wanted to specify my question, I've probably understood, what I thought wrong so far. So does segmentation work that a "segment" contains parts of the chromosomes with similar copy number properties? If so, than my question is the same: do the default parameters (e.g. critical value) work well for every whole exome sequencing data, or when should we modify them?

**Comment by veseshan** [comment]
Yes segmentation is the process of dividing the genome into contiguous regions of constant copy numbers. So you can infer the LOH status of HLA loci by looking at the segment(s) that contain them. The default parameters work well for whole exome sequencing of reasonable coverage.

**Comment by lhgergo** [comment]
Great, thanks!

**Comment by lidd77** [comment]
@lhgergo 
I don't think you can use FACETS to evaluate LOH in HLA region, because of this region's high polymorphic.
you cannot get accurate SNP loci via common tool mapping methods .
