### ISSUE TITLE
snp-pileup for only one chromosome

### ISSUE THREAD

**Issue by lhgergo** [mskcc/facets#80]
Hi!
We are only interested in copy number variations from chr6. Does it affect our results in any ways if we use vcf files, containing only chr6 SNPs as an input for snp-pileup?

Thanks!
Gergő

**Comment by veseshan** [comment]
snp-pileup should work fine. FACETS also works. However not having other chromosomes can make fitting the right copy number states hard.

**Comment by lhgergo** [comment]
All right, than I will keep all of them. Thank you!
