### ISSUE TITLE
the install facets

### ISSUE THREAD

**Issue by zhaohongqiangsoliva** [mskcc/facets#83]
I install_github("mskcc/facets",force=TRUE) 
Downloading GitHub repo mskcc/facets@master
from URL https://api.github.com/repos/mskcc/facets/zipball/master
Installation failed: error in running command
what's this

**Comment by veseshan** [comment]
No details on OS etc. There has been a report of installation troubles in CentOS cause by devtools. You may want to check that.

**Comment by zhaohongqiangsoliva** [comment]
thanks
