### ISSUE TITLE
Conda package update

### ISSUE THREAD

**Issue by pdiakumis** [mskcc/facets#97]
Hi, 

Thanks for the great package. Is it possible to update the conda package for Facets available at <https://anaconda.org/raylim/repo>? The version available there is from before December 2016 (I think it misses out on a few changes, since commit 9408da96).

This would help our group enormously, since we manage all our R packages via the conda system.

Many thanks - Peter

**Comment by ckandoth** [comment]
@raylim are you able to help with this? Otherwise, we can try and figure it out.

**Comment by veseshan** [comment]
Thanks @ckandoth @raylim

**Comment by micknudsen** [comment]
It would be awesome to get FACETS on bioconda, but I don't think it is possible without a LICENSE file. As far as I can see, there is no license information in this repository.

**Comment by veseshan** [comment]
The license under which it is released is in DESCRIPTION (following R package format). Is that sufficient or does there need to be a LICENSE file?

**Comment by micknudsen** [comment]
@veseshan Ah, sorry. I didn't notice that. I think this should be sufficient. The important part is just that there is a license. Time permitting, I will see if I can make a bioconda recipe.

**Comment by veseshan** [comment]
Thanks. Since facets depends on the data package pctGCdata you will need that too.

**Comment by pdiakumis** [comment]
I've got the pctGCdata conda recipe at https://github.com/pdiakumis/conda/tree/master/r-pctgcdata, in case it helps (conda pkg is at https://anaconda.org/pdiakumis/r-pctgcdata, but we can put it into bioconda).
I just couldn't get FACETS to compile properly or else I would have built that too.

**Comment by dariober** [comment]
Loosely related to this thread, I'm in the process of putting [cnv_facets](https://github.com/wwcrc/cnv_facets) (a command line wrapper of the facets pipeline) on bioconda. As part of that, I made [snp-pileup](https://bioconda.github.io/recipes/snp-pileup/README.html) available as a standalone package. Note that at the moment it is only available for the Linux platform.

As usual, many thanks to Venkat for making this code available!

**Comment by dariober** [comment]
After a wee bit of a struggle, [cnv_facets](https://github.com/wwcrc/cnv_facets) is now on [bioconda](https://bioconda.github.io/recipes/cnv_facets/README.html). 

Incidentally, the bioconda recipe installs the facets package and pctGCdata. To see which version of facets it installs, see the variable FACET_REF in [install_pkgs.R](https://github.com/wwcrc/cnv_facets/blob/master/install/install_pkgs.R) which refers to the hash sum of the git commit.
